# Generated by Django 2.1.4 on 2019-05-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0003_sendmail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Common',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('symptom_desc', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('medication', models.TextField()),
            ],
        ),
    ]
