# Generated by Django 2.1.4 on 2019-05-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0004_common'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnose',
            name='image',
            field=models.FileField(blank=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
